<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>串联多个任务</title>
</head>
<body>
    <script>
        let p = new Promise((resolve,reject) => {
            setTimeout(() => {
                resolve('ok')
            },1000)
        })
        p.then(value => {
            return new Promise((resolve,reject) => {  //这个回调返回的是一个成功的promise，后面的回调才会执行
                resolve("success")
                // reject('err')
            })
        }).then(value => {
            console.log(value);
            return new Promise(() => {}) //返回一个pending状态的回调函数，状态没有发生改变，后面的都不会执行
            // 这是中断promise链的唯一方法
        }).then(value => {
            return new Promise((resolve,reject) => {
                reject('错误')  //当有失败回调，后面的then方法都不在执行
            })
            console.log(value);  //undefined  由回调函数的返回值决定，上面的回调没有返回值，then方法的返回结果也是promise对象
        }).then(value => {
            console.log(333);  
            throw 'error!'
        }).catch(reason => {
            console.log(reason);  //异常穿透，直接写在最后就可以，在前面某一个回调函数返回一个失败的回调都可以处理
        })
    </script>
</body>
</html>