<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>async和await</title>
</head>
<body>
    <script>
        async function fn() { 
            // return 'aaa'
            // 返回的结果便是promise类型的对象， 就是一个成功的promise对象
            //  throw 抛出异常
            // 返回的是promise,由内部决定
            return new Promise((resolve,reject) => {
                // resolve('成功')
                reject('失败')
            })
         }
         const result = fn()
         result.then(value => {
             console.log(value);
         },reason => {
             console.warn(reason)
         })
         console.log(result);

         
         const p = new Promise((resolve,reject) => {
             resolve('成功')
            //  reject('失败')
            })
            async function main() { 
                // await 返回的结果就是promise成功的值
                try{

                    let result = await p
                    console.log(result);
                }catch(e) {
                    console.log(e);
                }
             }
             main()
    </script>
</body>
</html>